name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chechout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version ${{ github.event.Inputs.version }}
          git push origin master
          git push origin v${{ github.event.Inputs.version }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}